### PR TITLE
Add Linters

### PR DESCRIPTION
**Pull request by abdullah97-pro**

### CODE REVIEW

**Review by braincee — CHANGES_REQUESTED** [review]
Hello @abdullah97-pro 👋 , I am @braincee your Code Reviewer

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


so-close

HIGHLIGHTS
------
 - No linter errors ✅

REQUIRED CHANGES ♻️
------

- [x] Please as requested by the previous reviewer, I highly recommend updating your pull request title and description to make your repository look professional. This is a provided [link](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) of how to document pull request title and description professionally. 😄 
- [x] Please I recommend adding `test.md` file which has the text `This file should be ignored by git`. to the repository. 😄 
- [ ] Please I recommend adding the preferred Microverse README file per the project requirements as suggested by the previous reviewer. This is a provided [link](https://github.com/microverseinc/readme-template/blob/master/README.md) as suggested by the previous reviewer. 😄 

**_Please check the comments under the review._**

OPTIONAL CHANGES
--------
**_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @braincee in your question so I can receive the notification.

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._

----

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by jmonto55 — COMMENTED** [review]
Hi @abdullah97-pro 👋🏽, 

Great work on making the changes requested by a previous reviewer 👌
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

AlmostThereGIF
 ## Highlights

 ## Required Changes ♻️
- [x] Please kindly add a meaningful Pull Request title, and a detailed Pull Request description as requested by the previous reviewer 🤓. This is a very important good practice and one of the core requirements for this project 👇🏽
> Write short, detailed, easy to understand descriptions of pull requests. 

Here is a video showing you how to update your PR title and description, please kindly use it as reference while implementing the changes 👇🏽.

https://user-images.githubusercontent.com/116701485/234757272-042ecb36-0839-4df9-917d-3fb677e1f6f2.mp4

- [ ] Excellent work implementing your README file 💯. However, please kindly make sure to delete the Microverse logo from the file 👇🏽.

logo
- [ ] Also, please kindly fill all the sections inside your README file with the information about this project 🤓. Currently, the project has only the template information.

## Optional suggestions
- [ ] [OPTIONAL] Please I highly recommend sticking to the initial pull request until the project has been approved. This is a [Link](https://github.com/abdullah97-pro/repo/pull/1) to the initial pull request. 😃




_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by abdulhamiid — COMMENTED** [review]
# Status: Required Changes :recycle:
Hi @abdullah97-pro 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, I really appreciate the effort you put in! but there are still some which haven't been addressed yet.

Alt Text

## Highlights 🌟

- ✔️ Descriptions are descriptive
- ✔️ Linters checks are passing
- ✔️ Use GitHub Flow
- ✔️ Meaningful commit messages.

## Required Changes ♻️
_Please kindly check the comments under the review._

### 🏮 [REQUIRED] 🏮
- [x] As requested by the previous reviewer, please let's make our README file descriptive by customizing all sections of the [README template](https://github.com/microverseinc/readme-template) according to our project. 🛠💪

- [ ] A README file is a text file that describes and launches a project. It comprises information that is frequently needed to grasp the scope of the project. 🛠

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by GedeonTS — COMMENTED** [review]
# INVALID REVIEW REQUEST

Hi @abdullah97-pro , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a PR that has already been merged

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request merged**
